package main.java.com.xrusa.animals.enums;

public enum Action {

    PRINT_ACCOUNTS,
    PRINT_STATEMENTS,
    DEPOSIT,
    WITHDRAW,
    TRANSFER,
    BILL_PAY_WITH_RF,
    CREATE_STANDING_ORDER,
    DELETE_STANDING_ORDER,
    BILL_CREATE_WITH_RF,
    PRINT_CREATED_BILLS,
    PRINT_PAYED_BILLS,
    PRINT_CUSTOMERS,
    PRINT_AUDIT_LOG,
    MANUAL_BILL_PAYMENT,
    EXECUTE_STANDING_ORDER,
    CALCULATE_INTERESTS,
    BILL_EXTRAS

}
